import { db, bucket } from "../config/firebase.js";
import PDFDocument from "pdfkit";
import { formatTimestamp, sanitizeFilename } from "../utils/helpers.js";
import { NotFoundError } from "../utils/errors.js";

/**
 * Generate PDF report for medical records
 */
export async function generatePDFReport(patientId, records, userProfile) {
  if (!bucket) {
    throw new Error("PDF storage bucket is not configured");
  }

  const fileName = `medical-records-${patientId}-${Date.now()}.pdf`;
  const filePath = `exports/${sanitizeFilename(fileName)}`;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
    });

    // Create write stream to Firebase Storage
    const file = bucket.file(filePath);
    const stream = file.createWriteStream({
      metadata: {
        contentType: "application/pdf",
      },
    });

    doc.pipe(stream);

    // Header
    doc
      .fontSize(24)
      .font("Helvetica-Bold")
      .text("VitalTrack Medical Report", { align: "center" });

    doc.moveDown(0.5);
    doc
      .fontSize(12)
      .font("Helvetica")
      .text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });

    doc
      .moveTo(50, doc.y + 10)
      .lineTo(550, doc.y + 10)
      .stroke();
    doc.moveDown(1);

    // Patient Information
    doc.fontSize(14).font("Helvetica-Bold").text("Patient Information");

    doc.fontSize(11).font("Helvetica");
    doc.text(`Name: ${userProfile.name}`);
    doc.text(`Email: ${userProfile.email}`);
    doc.text(`Phone: ${userProfile.phone}`);
    doc.moveDown(0.5);

    // Records
    if (records.length === 0) {
      doc.text("No medical records found for the specified period.");
    } else {
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text(`Medical Records (${records.length})`);

      doc.moveDown(0.3);

      records.forEach((record, index) => {
        // Record header
        doc
          .fontSize(11)
          .font("Helvetica-Bold")
          .text(`Record ${index + 1}: ${record.disease.toUpperCase()}`);

        doc.fontSize(10).font("Helvetica");
        doc.text(
          `Date: ${new Date(record.createdAt.toDate ? record.createdAt.toDate() : record.createdAt).toLocaleString()}`,
        );

        // Record details in table format
        const details = [
          `Temperature: ${record.temperature || "N/A"}°C`,
          `Fluid Intake: ${record.fluidIntake || "N/A"}`,
          `Urine Output: ${record.urineOutput || "N/A"}`,
          `Urine Color: ${record.urineColor || "N/A"}`,
        ];

        details.forEach((detail) => {
          doc.text(detail, { indent: 20 });
        });

        // Symptoms
        if (record.symptoms && Object.values(record.symptoms).some((v) => v)) {
          doc.text("Symptoms:", { indent: 20 });
          Object.entries(record.symptoms).forEach(([symptom, present]) => {
            if (present) {
              const displayName = symptom
                .replace(/([A-Z])/g, " $1")
                .toLowerCase()
                .trim();
              doc.text(`• ${displayName}`, { indent: 40 });
            }
          });
        }

        // Notes
        if (record.notes) {
          doc.text(`Notes: ${record.notes}`, { indent: 20 });
        }

        doc.moveDown(0.5);
      });
    }

    // Footer
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
    doc
      .fontSize(9)
      .font("Helvetica")
      .text("This is an automated report generated by VitalTrack.", {
        align: "center",
      });
    doc.text(
      "Please consult with your healthcare provider for medical advice.",
      {
        align: "center",
      },
    );

    // Finalize PDF
    doc.end();

    // Handle stream events
    stream.on("finish", () => {
      resolve({
        fileName,
        filePath,
        url: `https://storage.googleapis.com/${bucket.name}/${filePath}`,
        size: stream.bytesWritten,
        createdAt: new Date(),
      });
    });

    stream.on("error", (error) => {
      reject(error);
    });

    doc.on("error", (error) => {
      reject(error);
    });
  });
}

/**
 * Get download URL for generated PDF
 */
export async function getPDFDownloadUrl(filePath) {
  if (!bucket) {
    throw new Error("PDF storage bucket is not configured");
  }

  const file = bucket.file(filePath);
  const exists = await file.exists();

  if (!exists[0]) {
    throw new NotFoundError("PDF file not found");
  }

  // Generate signed URL valid for 7 days
  const [signedUrl] = await file.getSignedUrl({
    version: "v4",
    action: "read",
    expires: Date.now() + 7 * 24 * 60 * 60 * 1000, // 7 days
  });

  return signedUrl;
}

/**
 * Delete old PDF files (cleanup)
 */
export async function deleteOldPDFs(daysOld = 30) {
  if (!bucket) {
    throw new Error("PDF storage bucket is not configured");
  }

  const cutoffDate = new Date(Date.now() - daysOld * 24 * 60 * 60 * 1000);

  const [files] = await bucket.getFiles({ prefix: "exports/" });

  let deletedCount = 0;

  for (const file of files) {
    const [metadata] = await file.getMetadata();
    const fileDate = new Date(metadata.timeCreated);

    if (fileDate < cutoffDate) {
      await file.delete();
      deletedCount++;
    }
  }

  return {
    deletedCount,
    cutoffDate,
  };
}

export default {
  generatePDFReport,
  getPDFDownloadUrl,
  deleteOldPDFs,
};
