const Map<String, Map<String, String>>
localized = <String, Map<String, String>>{
  'select_language': {'en': 'Select Language', 'si': 'භාෂාව තෝරන්න'},
  'select_language_subtitle': {
    'en': 'Choose your preferred app language',
    'si': 'ඔබ කැමති යෙදුම් භාෂාව තෝරන්න',
  },
  'language_english_title': {'en': 'English', 'si': 'English'},
  'language_english_subtitle': {'en': 'ENGLISH', 'si': 'ENGLISH'},
  'language_sinhala_title': {'en': 'සිංහල', 'si': 'සිංහල'},
  'language_sinhala_subtitle': {'en': 'SINHALA', 'si': 'SINHALA'},
  'splash_tagline': {
    'en': 'Track your health, secure your life',
    'si': 'ඔබේ සෞඛ්‍යය නිරීක්ෂණය කර ජීවිතය සුරක්ෂිත කරගන්න',
  },
  'login': {'en': 'Login', 'si': 'පිවිසීම'},
  'signup': {'en': 'SignUp', 'si': 'ලියාපදිංචි වීම'},
  'login_subtitle': {
    'en': 'Use your mobile number or email to continue',
    'si': 'ඉදිරියට යාම සඳහා ජංගම අංකය හෝ ඊමේල් භාවිතා කරන්න',
  },
  'signup_subtitle': {
    'en': 'Create your account in a few simple steps',
    'si': 'සරල පියවර කිහිපයකින් ඔබගේ ගිණුම සාදන්න',
  },
  'login_as': {'en': 'Login as', 'si': 'පිවිසෙන්න'},
  'patient': {'en': 'Patient', 'si': 'රෝගියා'},
  'caregiver': {'en': 'Caregiver', 'si': 'භාරකරු'},
  'login_method': {'en': 'Login method', 'si': 'පිවිසුම් ක්‍රමය'},
  'n4_number': {'en': 'Mobile Number', 'si': 'ජංගම දුරකථන අංකය'},
  'email': {'en': 'Email', 'si': 'ඊමේල්'},
  'password': {'en': 'Password', 'si': 'මුරපදය'},
  'continue': {'en': 'Continue', 'si': 'ඉදිරියට'},
  'no_account_signup': {
    'en': 'No account? Sign up',
    'si': 'ගිණුමක් නැද්ද? ලියාපදිංචි වන්න',
  },
  'required_field': {'en': 'Required field', 'si': 'අත්‍යවශ්‍ය ක්ෂේත්‍රය'},
  'invalid_email': {'en': 'Invalid email', 'si': 'වලංගු නොවන ඊමේල්'},
  'password_min': {
    'en': 'Password must be at least 6 characters',
    'si': 'මුරපදය අක්ෂර 6ක් හෝ වැඩි විය යුතුයි',
  },
  'otp_verification': {'en': 'OTP Verification', 'si': 'OTP තහවුරු කිරීම'},
  'enter_otp_login': {
    'en': 'Enter OTP sent for login',
    'si': 'පිවිසීම සඳහා OTP ඇතුල් කරන්න',
  },
  'phone_otp_verification': {
    'en': 'Phone OTP Verification',
    'si': 'දුරකථන OTP තහවුරු කිරීම',
  },
  'enter_otp_signup': {
    'en': 'Enter OTP sent to your phone number',
    'si': 'ඔබගේ දුරකථන අංකයට එවා ඇති OTP ඇතුල් කරන්න',
  },
  'otp_code': {'en': 'OTP Code', 'si': 'OTP කේතය'},
  'verify': {'en': 'Verify', 'si': 'තහවුරු කරන්න'},
  'enter_valid_otp': {
    'en': 'Enter valid 6 digit OTP',
    'si': 'වලංගු 6 ඉලක්කම් OTP ඇතුල් කරන්න',
  },
  'send_otp_failed': {
    'en': 'Failed to send OTP. Please try again.',
    'si': 'OTP යැවීමට අසමත් විය. කරුණාකර නැවත උත්සාහ කරන්න.',
  },
  'otp_verify_failed': {
    'en': 'OTP verification failed. Please try again.',
    'si': 'OTP තහවුරු කිරීම අසාර්ථකයි. කරුණාකර නැවත උත්සාහ කරන්න.',
  },
  'email_exists_error': {
    'en':
        'This email is already registered. Please log in or use a different email.',
    'si':
        'මෙම ඊමේල් ලිපිනය දැනටමත් ලියාපදිංචි වී ඇත. කරුණාකර පිවිසෙන්න හෝ වෙනත් ඊමේල් එකක් භාවිතා කරන්න.',
  },
  'phone_exists_error': {
    'en':
        'This phone number is already registered. Please log in or use a different phone number.',
    'si':
        'මෙම දුරකථන අංකය දැනටමත් ලියාපදිංචි වී ඇත. කරුණාකර පිවිසෙන්න හෝ වෙනත් අංකයක් භාවිතා කරන්න.',
  },
  'invalid_otp_error': {
    'en': 'Invalid OTP. Please check the code and try again.',
    'si': 'වලංගු නොවන OTP. කේතය පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
  },
  'otp_expired_error': {
    'en': 'OTP expired or not found. Please request a new OTP.',
    'si': 'OTP කල් ඉකුත් වී ඇත හෝ සොයාගත නොහැක. කරුණාකර නව OTP එකක් ඉල්ලන්න.',
  },
  'email_otp_send_failed': {
    'en': 'Failed to send OTP to email.',
    'si': 'ඊමේල් වෙත OTP යැවීමට අසමත් විය.',
  },
  'name': {'en': 'Name', 'si': 'නම'},
  'phone_number_lk': {'en': 'Mobile Number', 'si': 'ජංගම දුරකථන අංකය'},
  'optional': {'en': 'optional', 'si': 'අවශ්‍ය නැත'},
  're_enter_password': {
    'en': 'Re-enter Password',
    'si': 'මුරපදය නැවත ඇතුල් කරන්න',
  },
  'password_mismatch': {
    'en': 'Passwords do not match',
    'si': 'මුරපද දෙක එකිනෙකට නොගැලපේ',
  },
  'create_account': {'en': 'Create Account', 'si': 'ගිණුම සාදන්න'},
  'invalid_lk_phone': {
    'en': 'Enter valid Sri Lankan mobile number',
    'si': 'වලංගු ශ්‍රී ලාංකීය ජංගම අංකයක් ඇතුල් කරන්න',
  },
  'keep_records': {'en': 'Keep Records', 'si': 'දත්ත තබාගන්න'},
  'show_records': {'en': 'Show Records', 'si': 'වාර්තා පෙන්වන්න'},
  'profile': {'en': 'Profile', 'si': 'පැතිකඩ'},
  'hotspot_map': {'en': 'Hotspot Map', 'si': 'හොට්ස්පොට් සිතියම'},
  'patients': {'en': 'Patients', 'si': 'රෝගීන්'},
  'select_disease': {'en': 'Select disease', 'si': 'රෝගය තෝරන්න'},
  'dengue': {'en': 'Dengue', 'si': 'ඩෙංගු'},
  'rat_fever': {'en': 'Rat Fever', 'si': 'මී උණ'},
  'add_record': {'en': 'Add Record', 'si': 'වාර්තාව එක් කරන්න'},
  'body_temperature': {'en': 'Body Temperature', 'si': 'ශරීර උෂ්ණත්වය'},
  'fluid_intake_ml': {'en': 'Fluid Intake (ml)', 'si': 'දියර ප්‍රමාණය (ml)'},
  'urine_output_ml': {'en': 'Urine Output (ml)', 'si': 'මුත්‍රා ප්‍රමාණය (ml)'},
  'urine_color': {'en': 'Urine Color', 'si': 'මුත්‍රා වර්ණය'},
  'body_pain': {'en': 'Body Pain', 'si': 'ශරීර වේදනාව'},
  'vomiting': {'en': 'Vomiting', 'si': 'වමනය'},
  'additional_notes': {'en': 'Additional Notes', 'si': 'අමතර සටහන්'},
  'save': {'en': 'Save', 'si': 'සුරකින්න'},
  'saved': {'en': 'Saved', 'si': 'සුරක්ෂිතයි'},
  'record_saved': {
    'en': 'Record saved with date and time',
    'si': 'දිනය සහ වේලාව සමඟ වාර්තාව සුරකින ලදී',
  },
  'last_24h': {'en': 'Last 24 hours', 'si': 'පසුගිය පැය 24'},
  'last_3_days': {'en': 'Last 3 days', 'si': 'පසුගිය දින 3'},
  'last_7_days': {'en': 'Last 7 days', 'si': 'පසුගිය දින 7'},
  'export_pdf': {'en': 'Export PDF', 'si': 'PDF අපනයනය'},
  'no_records': {
    'en': 'No records for selected timeline',
    'si': 'තෝරාගත් කාලරාමුව සඳහා වාර්තා නොමැත',
  },
  'phone': {'en': 'Phone Number', 'si': 'දුරකථන අංකය'},
  'verify_email': {'en': 'Verify Email', 'si': 'ඊමේල් තහවුරු කරන්න'},
  'verified': {'en': 'Verified', 'si': 'තහවුරුයි'},
  'email_verification': {
    'en': 'Email Verification',
    'si': 'ඊමේල් තහවුරු කිරීම',
  },
  'enter_email_otp': {
    'en': 'Enter OTP sent to email',
    'si': 'ඊමේල් වෙත එවූ OTP ඇතුල් කරන්න',
  },
  'email_verified': {'en': 'Email verified', 'si': 'ඊමේල් තහවුරු කරන ලදි'},
  'profile_updated': {
    'en': 'Profile updated',
    'si': 'පැතිකඩ යාවත්කාලීන කරන ලදි',
  },
  'add_caregiver': {'en': 'Add Caregiver', 'si': 'භාරකරුවෙකු එක් කරන්න'},
  'caregiver_code': {'en': 'Caregiver Code', 'si': 'භාරකරු කේතය'},
  'generate_6_digit_code': {
    'en': 'Generate 6 Digit Code',
    'si': 'අංක 6 ක කේතයක් ජනනය කරන්න',
  },
  'caregivers_list': {'en': 'Caregivers List', 'si': 'භාරකරුවන්ගේ ලැයිස්තුව'},
  'no_caregivers_yet': {'en': 'No caregivers yet', 'si': 'තව භාරකරුවන් නැත'},
  'close': {'en': 'Close', 'si': 'වසන්න'},
  'logout': {'en': 'Logout', 'si': 'ඉවත්වන්න'},
  'hotspot_map_placeholder': {
    'en': 'Hotspot Map Preview',
    'si': 'හොට්ස්පොට් සිතියම් පෙරදසුන',
  },
  'add_hotspot_data': {
    'en': 'Add hotspot data',
    'si': 'හොට්ස්පොට් දත්ත එක් කරන්න',
  },
  'add_patient_hotspot_data': {
    'en': 'Add patients hotspot data',
    'si': 'රෝගීන්ගේ හොට්ස්පොට් දත්ත එක් කරන්න',
  },
  'patient_name': {'en': 'Patient Name', 'si': 'රෝගියාගේ නම'},
  'hometown': {'en': 'Hometown', 'si': 'ගම'},
  'workplace': {'en': 'Workplace', 'si': 'රැකියා ස්ථානය'},
  'places_last_3_days': {
    'en': 'Places visited in last 3 days',
    'si': 'පසුගිය දින 3 තුළ ගිය ස්ථාන',
  },
  'recent_submissions': {'en': 'Recent submissions', 'si': 'නවතම දත්ත'},
  'no_data': {'en': 'No data available', 'si': 'දත්ත නොමැත'},
  'add_patient': {'en': 'Add Patient', 'si': 'රෝගියා එක් කරන්න'},
  'no_patients': {'en': 'No patients added yet', 'si': 'තව රෝගීන් එක්කර නැත'},
  'use_6_digit_code': {
    'en': 'Use 6 digit code',
    'si': 'අංක 6 ක කේතය භාවිතා කරන්න',
  },
  'create_new_patient': {
    'en': 'Create new patient',
    'si': 'නව රෝගියෙකු සාදන්න',
  },
  'invalid_code': {'en': 'Invalid code', 'si': 'වලංගු නොවන කේතය'},
  'patient_added': {'en': 'Patient added', 'si': 'රෝගියා එක් කරන ලදි'},
  'confirm': {'en': 'Confirm', 'si': 'තහවුරු කරන්න'},
  'yes': {'en': 'Yes', 'si': 'ඔව්'},
  'no': {'en': 'No', 'si': 'නැහැ'},
  'share_this_code_with_caregiver': {
    'en': 'Share this code with your caregiver',
    'si': 'මෙම කේතය ඔබගේ භාරකරුට බෙදා දෙන්න',
  },
  'code_copied': {
    'en': 'Code copied to clipboard',
    'si': 'කේතය පසුරු පුවරුවට පිටපත් කරන ලදි',
  },
  'copy': {'en': 'Copy', 'si': 'පිටපත් කරන්න'},
  'link_to_patient': {'en': 'Link to Patient', 'si': 'රෝගියා වෙත සම්බන්ධ වන්න'},
  'enter_patient_code': {
    'en': 'Enter Patient Code',
    'si': 'රෝගියාගේ කේතය ඇතුල් කරන්න',
  },
  'patient_code': {'en': 'Patient Code', 'si': 'රෝගියාගේ කේතය'},
  'my_patients': {'en': 'My Patients', 'si': 'මගේ රෝගීන්'},
  'no_patients_yet': {'en': 'No patients yet', 'si': 'තවම රෝගීන් නැත'},
  'patient_linked': {
    'en': 'Patient linked successfully',
    'si': 'රෝගියා සफලයෙන් සම්බන්ධ වුණි',
  },
  'cancel': {'en': 'Cancel', 'si': 'අවලංගු කරන්න'},
  'link': {'en': 'Link', 'si': 'සම්බන්ධ කරන්න'},
  'error': {'en': 'Error', 'si': 'දෝෂය'},
  'export_failed': {'en': 'Failed to export PDF', 'si': 'PDF අපනයනය අසාර්ථකයි'},
  'refreshing': {'en': 'Refreshing...', 'si': 'යාවත්කාලීන වෙමින්...'},
  'pdf_downloaded': {
    'en': 'PDF downloaded successfully',
    'si': 'PDF සफලයෙන් බාගත කරන ලදි',
  },
  'cannot_open_pdf': {
    'en': 'Cannot open PDF. Please try again.',
    'si': 'PDF විවෘත කළ නොහැක. කරුණාකර නැවත උත්සාහ කරන්න.',
  },
};
