// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByljrj6be523aJx7dPPu7YiTGpI6y7vW0',
    appId: '1:214909467704:web:927edf1503b2d189d03acd',
    messagingSenderId: '214909467704',
    projectId: 'vitaltrack-ce9e1',
    authDomain: 'vitaltrack-ce9e1.firebaseapp.com',
    storageBucket: 'vitaltrack-ce9e1.firebasestorage.app',
    measurementId: 'G-2XSC4X7Q4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACcoK3NzLkEAApcLyumCr2wAN-87_QBH4',
    appId: '1:214909467704:android:b6c3a083b415e732d03acd',
    messagingSenderId: '214909467704',
    projectId: 'vitaltrack-ce9e1',
    storageBucket: 'vitaltrack-ce9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2yYGWIemGy6vjOO8_CzubV4Msq6xOegE',
    appId: '1:214909467704:ios:ef811e037b4a1ef2d03acd',
    messagingSenderId: '214909467704',
    projectId: 'vitaltrack-ce9e1',
    storageBucket: 'vitaltrack-ce9e1.firebasestorage.app',
    iosBundleId: 'com.example.vitalTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2yYGWIemGy6vjOO8_CzubV4Msq6xOegE',
    appId: '1:214909467704:ios:ef811e037b4a1ef2d03acd',
    messagingSenderId: '214909467704',
    projectId: 'vitaltrack-ce9e1',
    storageBucket: 'vitaltrack-ce9e1.firebasestorage.app',
    iosBundleId: 'com.example.vitalTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByljrj6be523aJx7dPPu7YiTGpI6y7vW0',
    appId: '1:214909467704:web:1e09c963b81ba5a2d03acd',
    messagingSenderId: '214909467704',
    projectId: 'vitaltrack-ce9e1',
    authDomain: 'vitaltrack-ce9e1.firebaseapp.com',
    storageBucket: 'vitaltrack-ce9e1.firebasestorage.app',
    measurementId: 'G-1VWQWBDDZW',
  );

}