// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7DtcmiMBRkU1qd4Bq5s7vKxaS1fU38kc',
    appId: '1:970889451531:web:your_web_app_id',
    messagingSenderId: '970889451531',
    projectId: 'vitaltrack-92f93',
    authDomain: 'vitaltrack-92f93.firebaseapp.com',
    storageBucket: 'vitaltrack-92f93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7DtcmiMBRkU1qd4Bq5s7vKxaS1fU38kc',
    appId: '1:970889451531:android:7afdba6071c4fea396cf0e',
    messagingSenderId: '970889451531',
    projectId: 'vitaltrack-92f93',
    storageBucket: 'vitaltrack-92f93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7DtcmiMBRkU1qd4Bq5s7vKxaS1fU38kc',
    appId: '1:970889451531:ios:your_ios_app_id',
    messagingSenderId: '970889451531',
    projectId: 'vitaltrack-92f93',
    storageBucket: 'vitaltrack-92f93.firebasestorage.app',
    iosBundleId: 'com.example.vitalTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7DtcmiMBRkU1qd4Bq5s7vKxaS1fU38kc',
    appId: '1:970889451531:ios:your_ios_app_id',
    messagingSenderId: '970889451531',
    projectId: 'vitaltrack-92f93',
    storageBucket: 'vitaltrack-92f93.firebasestorage.app',
    iosBundleId: 'com.example.vitalTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7DtcmiMBRkU1qd4Bq5s7vKxaS1fU38kc',
    appId: '1:970889451531:web:your_windows_app_id',
    messagingSenderId: '970889451531',
    projectId: 'vitaltrack-92f93',
    authDomain: 'vitaltrack-92f93.firebaseapp.com',
    storageBucket: 'vitaltrack-92f93.firebasestorage.app',
  );
}
